services:
  neo4j:
    image: neo4j:community
    container_name: nlp-neo4j

    ports:
      - "7474:7474"
      - "7687:7687"

    environment:
      NEO4J_AUTH: neo4j/aletheia2026

    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
